### ISSUE TITLE
Error in actions

### ISSUE THREAD

**Issue by ulimartinez** [HackDFW/hackdfw-game-frontend#1]
The following error is thrown while cylcing through states:

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://game.hackdfw.com' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by bearcott** [comment]
hopefully fixed! xd
